# Site settings
encoding: utf-8

title: Polymer Redux
heading: Polymer ❤ Redux
tagline: Polymer bindings for Redux.

baseurl: ""
url: "http://tur-nr.github.io/polymer-redux"

# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
